version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./database/postgresql/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django-server:
    image: delab-server:latest
    command: DJANGO_DATABASE='postgres' python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  migration:
    image: delab-server:latest
    command: python manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - db
  train_sentiment_model:
    image: delab-server:latest
    command: python manage.py runscript train_sentiment_classifier
    volumes:
      - .:/code
    depends_on:
      - db
  process_tasks:
    image: delab-server:latest
    command: python manage.py process_tasks -v 2 --log-std --duration -1
    volumes:
      - .:/code
    depends_on:
      - migration

