version: "3.3"

services:
  postgres:
    image: postgres
    volumes:
      - ./database/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/

  migrate:
    image: delab-server
    command: bash -c "python manage.py makemigrations blog delab users && python manage.py migrate --noinput && python manage.py createsuperuser --noinput"
    volumes:
      - ./logs/migrate:/code/logs
      - ./database/migrations/delab:/code/delab/migrations
      - ./database/migrations/blog:/code/blog/migrations
      - ./database/migrations/users:/code/users/migrations
    depends_on:
      - postgres
    environment:
      - DJANGO_DATABASE=postgres
      - DJANGO_SUPERUSER_PASSWORD=delab
      - DJANGO_SUPERUSER_USERNAME=delab
      - DJANGO_SUPERUSER_EMAIL=julian.dehne@uni-goettingen.de

  run_server:
    image: delab-server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./logs/server:/code/logs
      - ./database/media:/code/media
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - migrate
    environment:
      - DJANGO_DATABASE=postgres

  process_tasks:
    image: delab-server
    command: python manage.py process_tasks -v 2 --log-std --duration -1 --sleep 20
    volumes:
      - ./logs/tasks:/code/logs
      - ./model:/code/model
      - ./database/media:/code/media
    depends_on:
      - migrate
    environment:
      - DJANGO_DATABASE=postgres

  download_intolerant_tweets:
    image: delab-server
    command: python manage.py runscript download_terrible_tweets
    depends_on:
      - process_tasks
    environment:
      - DJANGO_DATABASE=postgres

