version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./database/postgresql/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  migration:
    build: .
    image: delab-server
    command: python manage.py makemigrations
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - DJANGO_DATABASE=postgres

  makemigration:
    build: .
    image: delab-server
    command: python manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - migration
    environment:
      - DJANGO_DATABASE=postgres

  run_server:
    build: .
    image: delab-server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - makemigration
    environment:
      - DJANGO_DATABASE=postgres


